spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: allocation-service
              uri: lb://ALLOCATION-SERVICE
              predicates:
                - Path=/allocation/**
              filters:
                - AuthenticationFilter
                - RoleAuthorizationFilter

            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/employees/**
              filters:
                - AuthenticationFilter
                - RoleAuthorizationFilter

            - id: project-service
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/project/**
              filters:
                - AuthenticationFilter
                - RoleAuthorizationFilter

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - RoleAuthorizationFilter
